version: '3'
services:
    cells:
        image: 36bian/meow:1.0
        restart: unless-stopped
        volumes: ["meow:/root/.meow"] #修改配置文件后重启容器
        ports: ["7777:7777"]
        environment:
            - hostip=${myip} # 修改成自己主机ip

volumes:
    meow: {}
