version: '2.0'

services:
  jellyfin:
    restart: unless-stopped
    image: jellyfin/jellyfin:10.4.0
    ports:
      - 8096:8096
      - 8920:8920
    volumes:
      - ./config:/config
      - ./cache:/cache
      - /var/home/share:/media